kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appa-cr-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appa-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appa-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appa-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appa-cr-role
subjects:
- kind: ServiceAccount
  name: appa-sa
  namespace: {{.namespace}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: appa-sa-binding
subjects:
- kind: ServiceAccount
  name: appa-sa
roleRef:
  kind: Role
  name: appa-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
spec:
 selector:
   matchLabels:
     networkservicemesh.io/app: "nsm-app"
     networkservicemesh.io/impl: "appb"
     app: appb
 replicas: 1
 template:
   metadata:
     labels:
       networkservicemesh.io/app: "nsm-app"
       networkservicemesh.io/impl: "appb"
       app: appb
   spec:
     containers:
       - name: sidecar-endpoint
         image: networkservicemesh/proxy-sidecar-nse:master
         imagePullPolicy: IfNotPresent
         env:
           - name: ADVERTISE_NSE_NAME
             value: "nsm-app"
           - name: ADVERTISE_NSE_LABELS
             value: "app=appb"
           - name: TRACER_ENABLED
             value: "true"
           - name: IP_ADDRESS
             value: "10.60.1.0/24"
         resources:
           limits:
             networkservicemesh.io/socket: 1
       - name: appb
         image: layer5/meshery-nsm-sample-appb
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 80
metadata:
 name: appb
 labels:
   app: appb
---
apiVersion: apps/v1
kind: Deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     networkservicemesh.io/app: "appa"
     app: appa
 template:
   metadata:
     labels:
       networkservicemesh.io/app: "appa"
       app: appa
   spec:
     serviceAccountName: appa-sa
     containers:
       - name: appa
         image: layer5/meshery-nsm-sample-appa
         ports:
           - containerPort: 80
         env:
          - name: URL
            value: http://appb/
          - name: IP_ADDRESS
            value: "10.60.1.0/24"
metadata:
 name: appa
 labels:
   app: appa
 annotations:
   ns.networkservicemesh.io: nsm-app?app=appa
---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: nsm-app
spec:
  payload: HTTP
  matches:
    - match:
      sourceSelector:
        app: appa
      route:
        - destination:
          destinationSelector:
            app: appb
---
apiVersion: v1
kind: Service
metadata:
  name: appa
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: appa
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: appb
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: appb
  type: LoadBalancer
status:
  loadBalancer: {}
---